### ISSUE TITLE
SBZV: Project DIVA Arcade not working on v1-dev aqua.jar

### ISSUE THREAD

**Issue by Sensokaku** [hykilpikonna/AquaDX#15]
I've been trying to play Project Diva Arcade 7.10 but it doesn't work using a v1-dev aqua.jar i built, I have played maimai dx buddies on it so i know that it does work at least. Project Diva Arcade does work on the latest nightly build though so it's something that's been added to v1-dev branch.

**Comment by hykilpikonna** [comment]
What does the log say?

I haven't tested Diva on v1-dev yet since none of my friends play Diva on actual HDD, would you help me with the testing?

Also, please join our discord: https://discord.gg/NhJzhCcg

**Comment by hykilpikonna** [comment]
Solved in 2fa153e569c7b7e3b46a9522ba79e073be38212d
