### ISSUE TITLE
SQLite isn't supported in the v1 development branch yet. Please either switch to MariaDB or wait for the stable v1 release.

### ISSUE THREAD

**Issue by byf3332** [hykilpikonna/AquaDX#25]
I tried to build one for using with Lunimous, and when I launch  the jar I encounter this: 

``!!! ERROR !!!``
``SQLite isn't supported in the v1 development branch yet.``
``Please either switch to MariaDB or wait for the stable v1 release.``

Either using actions or build locally on my windows pc results the same. Is there a way to fix? 
Thx a lot

<details> <summary>Logs</summary>

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.2.3)

04-02 20:24:22 INFO  ENTRYK | EntryKt                                  : Starting EntryKt v1.0.0 using Java 21.0.2 with PID 12432 (X:\aqua-nightly\aqua.jar started by buyifan in X:\aqua-nightly)
04-02 20:24:22 INFO  ENTRYK | EntryKt                                  : No active profile set, falling back to 1 default profile: "default"
04-02 20:24:24 INFO  SYSTEM | .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
04-02 20:24:24 INFO  SYSTEM | .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 439 ms. Found 154 JPA repository interfaces.
04-02 20:24:25 INFO  SYSTEM | o.s.b.w.e.j.JettyServletWebServerFactory : Server initialized with port: 80
04-02 20:24:26 INFO  SYSTEM | org.eclipse.jetty.server.Server          : jetty-12.0.6; built: 2024-01-30T02:43:24.387Z; git: 78ab6e6ba163f89cdd97f2ae0283fbb5e371cfaf; jvm 21.0.2+13-LTS-58
04-02 20:24:26 INFO  SYSTEM | o.e.j.s.h.ContextHandler.application     : Initializing Spring embedded WebApplicationContext
04-02 20:24:26 INFO  SYSTEM | w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 3220 ms
04-02 20:24:26 INFO  SYSTEM | o.e.j.session.DefaultSessionIdManager    : Session workerName=node0
04-02 20:24:26 INFO  SYSTEM | o.e.jetty.server.handler.ContextHandler  : Started osbwej.JettyEmbeddedWebAppContext@613a608e{application,/,b=file:/C:/Users/buyifan/AppData/Local/Temp/jetty-docbase.80.18428362824564727769/,a=AVAILABLE,h=oeje10s.SessionHandler@37b1218{STARTED}}
04-02 20:24:26 INFO  SYSTEM | o.e.j.e.servlet.ServletContextHandler    : Started osbwej.JettyEmbeddedWebAppContext@613a608e{application,/,b=file:/C:/Users/buyifan/AppData/Local/Temp/jetty-docbase.80.18428362824564727769/,a=AVAILABLE,h=oeje10s.SessionHandler@37b1218{STARTED}}
04-02 20:24:26 INFO  SYSTEM | org.eclipse.jetty.server.Server          : Started oejs.Server@42150951{STARTING}[12.0.6,sto=0] @5465ms
04-02 20:24:26 INFO  SYSTEM | com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
04-02 20:24:26 INFO  SYSTEM | com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@79982bcc
04-02 20:24:26 INFO  SYSTEM | com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
04-02 20:24:26 INFO  SYSTEM | org.flywaydb.core.FlywayExecutor         : Database: jdbc:sqlite:data/db.sqlite (SQLite 3.45)
04-02 20:24:27 INFO  SYSTEM | o.f.core.internal.command.DbValidate     : Successfully validated 158 migrations (execution time 00:00.136s)
04-02 20:24:27 INFO  SYSTEM | o.f.core.internal.command.DbMigrate      : Current version of schema "main": 257
04-02 20:24:27 WARN  SYSTEM | o.f.core.internal.command.DbMigrate      : outOfOrder mode is active. Migration of schema "main" may not be reproducible.
04-02 20:24:27 INFO  SYSTEM | o.f.core.internal.command.DbMigrate      : Schema "main" is up to date. No migration necessary.
04-02 20:24:27 INFO  SYSTEM | o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
04-02 20:24:27 INFO  SYSTEM | org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.4.4.Final
04-02 20:24:27 INFO  SYSTEM | o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
04-02 20:24:27 INFO  SYSTEM | o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
04-02 20:24:29 INFO  SYSTEM | o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
04-02 20:24:29 INFO  SYSTEM | j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
04-02 20:24:30 INFO  SYSTEM | o.s.d.j.r.query.QueryEnhancerFactory     : Hibernate is in classpath; If applicable, HQL parser will be used.
04-02 20:24:34 WARN  NET    | net.components.JWT                       : JWT Secret is less than 256 bits, padding with 0. PLEASE USE A STRONGER SECRET!
04-02 20:24:34 INFO  NET    | net.components.JWT                       : JWT Service Enabled
04-02 20:24:34 INFO  NET    | net.components.GeoIP                     : GeoIP Service Enabled
04-02 20:24:34 WARN  SYSTEM | ext.Ext                                  : Resource /meta/chu3/music.json is not found
04-02 20:24:34 WARN  SYSTEM | ext.Ext                                  : Resource /meta/chu3/items.json is not found
04-02 20:24:34 WARN  SYSTEM | ext.Ext                                  : Resource /meta/mai2/music.json is not found
04-02 20:24:34 WARN  SYSTEM | ext.Ext                                  : Resource /meta/mai2/items.json is not found
04-02 20:24:34 WARN  SYSTEM | ext.Ext                                  : Resource /meta/ongeki/music.json is not found
04-02 20:24:34 WARN  SYSTEM | ext.Ext                                  : Resource /meta/ongeki/items.json is not found
04-02 20:24:34 WARN  SYSTEM | ext.Ext                                  : Resource /meta/wacca/music.json is not found
04-02 20:24:34 WARN  MAIMAI | maimai2.handler.GetUserItemHandler       : Mai2 music info is empty
04-02 20:24:34 WARN  MAIMAI | maimai2.handler.GetUserItemHandler       : Mai2 item info is empty
!!! ERROR !!!
SQLite isn't supported in the v1 development branch yet.
Please either switch to MariaDB or wait for the stable v1 release.
</details>

**Comment by hykilpikonna** [comment]
The v1 branch is still in development, and I haven't supported SQLite database yet. In the config file `config/application.properties`, change your database to a MariaDB server instead.

If you don't know how to do that, an easy way is to download and install Docker, clone the repo, and run `docker compose up` in repo root. 

Or you can just make and account and use the public instance https://aquadx.net instead.

**Comment by byf3332** [comment]
Much thanks
Successfully set up using docker
