### ISSUE TITLE
ALL.NET AUTHENTICATION BAD

### ISSUE THREAD

**Issue by HajiAIqaq** [hykilpikonna/AquaDX#26]
I fork the Repositories and build it, but when I use AquaDX nightly for Luminous,the game return ALL.NET AUTHENTICATION BAD,THX
![屏幕截图 2024-04-06 131256](https://github.com/hykilpikonna/AquaDX/assets/130824562/622fdb0d-fab0-4975-9a77-2871f27ec9aa)
![4dcce432ac10906789f72f2ffb10284a](https://github.com/hykilpikonna/AquaDX/assets/130824562/a929bb94-6fa1-44c2-b5b0-d0602df3fbee)

**Comment by hykilpikonna** [comment]
Hmm... I'm on the same version but I don't have this issue. Maybe try the following:

1. Change `"type": "2.0"` to `"1.0"` under `allnet_auth` in `config_common.json`
2. Change `"enable": true` to false under `allnet_accounting` in `config_common.json`
3. I don't think this is the case but if you have a clean binary, you need to patch it to disable encryption using https://performai.evilleaker.com/chusanlmnjp.html
4. Try using our official https://aquadx.net server?

Please let me know if any of them work or don't work.

**Comment by HajiAIqaq** [comment]
I try that,it doesn't work

**Comment by HajiAIqaq** [comment]
ISP in China will block naominet.jp when you use server in it,it cause ALL.NET AUTHENTICATION BAD
