### ISSUE TITLE
Title Server BAD

### ISSUE THREAD

**Issue by HajiAIqaq** [hykilpikonna/AquaDX#38]
log:
'''
06-01 05:01:48 INFO  ALLNET | allnet.AllNet                            : AllNet /PowerOn : {game_id=SDHD, ver=2.22, serial=A28E88E2109, ip=192.168.139.1, firm_ver=60001, boot_ver=0000, encode=UTF-8, format_ver=3, hops=1, token=359549296}
06-01 05:01:48 INFO  ALLNET | allnet.AllNet                            : > Response: {stat=1, name=, place_id=123, region0=1, region_name0=W, region_name1=X, region_name2=Y, region_name3=Z, country=JPN, nickname=AquaDX, uri=http://172.19.0.3:80/g/chu3/2.22/, host=172.19.0.3, allnet_id=456, client_timezone=+0900, utc_time=2024-06-01T05:01:48Z, setting=, res_ver=3, token=359549296}
06-01 05:01:48 INFO  AIMEDB | aimedb.AimeDB                            : AimeDB /Campaign : (game SDHD, keychip A28E88E2109)
06-01 05:01:48 INFO  ALLNET | allnet.AllNet                            : AllNet /DownloadOrder : {game_id=SDHD, ver=2.22, serial=A28E88E2109, encode=UTF-8}
06-01 05:01:48 INFO  ALLNET | allnet.AllNet                            : > Response: {stat=1, serial=A28E88E2109}
06-01 05:02:34 INFO  AIMEDB | aimedb.AimeDB                            : AimeDB /Campaign : (game SDHD, keychip A28E88E2109)
06-01 05:02:59 INFO  ALLNET | allnet.AllNet                            : AllNet /PowerOn : {game_id=SDHD, ver=2.22, serial=A28E88E2109, ip=192.168.139.1, firm_ver=60001, boot_ver=0000, encode=UTF-8, format_ver=3, hops=1, token=3391434839}
06-01 05:02:59 INFO  ALLNET | allnet.AllNet                            : > Response: {stat=1, name=, place_id=123, region0=1, region_name0=W, region_name1=X, region_name2=Y, region_name3=Z, country=JPN, nickname=AquaDX, uri=http://172.19.0.3:80/g/chu3/2.22/, host=172.19.0.3, allnet_id=456, client_timezone=+0900, utc_time=2024-06-01T05:02:59Z, setting=, res_ver=3, token=3391434839}
06-01 05:02:59 INFO  AIMEDB | aimedb.AimeDB                            : AimeDB /Campaign : (game SDHD, keychip A28E88E2109)
06-01 05:02:59 INFO  ALLNET | allnet.AllNet                            : AllNet /DownloadOrder : {game_id=SDHD, ver=2.22, serial=A28E88E2109, encode=UTF-8}
06-01 05:02:59 INFO  ALLNET | allnet.AllNet                            : > Response: {stat=1, serial=A28E88E2109}
06-01 05:04:01 INFO  AIMEDB | aimedb.AimeDB                            : AimeDB /Campaign : (game SDHD, keychip A28E88E2109)
'''
I guess it doesn't support 2.22?

**Comment by hykilpikonna** [comment]
Yea nobody tested it on 2.22 yet so probably it doesn't support 2.22

**Comment by HajiAIqaq** [comment]
I test on ongeki 1.45-A，it also return title server bad,how i can fix it

**Comment by hykilpikonna** [comment]
Hmmmm I just realized today when I look at it, is "172.19.0.3" the docker container's IP? I know that docker on Windows have a bug where the host cannot access the docker IP directly... maybe changing the server address to 192.168.139.1 in config would help.
