### ISSUE TITLE
Matching Server BAD

### ISSUE THREAD

**Issue by toreew** [hykilpikonna/AquaDX#44]
[log.txt](https://github.com/user-attachments/files/15945179/log.txt)
![화면 캡처 2024-06-24 002047](https://github.com/hykilpikonna/AquaDX/assets/117936507/f60e3285-f0a9-4332-8a91-53b2d515b448)
I'm trying to run SDHD 2.20 and it won't run online because of this.

**Comment by Keeboy99** [comment]
> [log.txt](https://github.com/user-attachments/files/15945179/log.txt) ![화면 캡처 2024-06-24 002047](https://private-user-images.githubusercontent.com/117936507/342078293-f60e3285-f0a9-4332-8a91-53b2d515b448.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjIzMzYsIm5iZiI6MTcxOTE2MjAzNiwicGF0aCI6Ii8xMTc5MzY1MDcvMzQyMDc4MjkzLWY2MGUzMjg1LWYwYTktNDMzMi04YTkxLTUzYjJkNTE1YjQ0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QxNzAwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzdmOWM2NWM4Nzk4MTM1ZGY4NzIwZDhhZmJlNWRlY2M0NTk3NTBkNWYyMGJhYjM2ZDYwOWYwNjllMDE1YTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oqal-hBGZUXosA9sMFs8NhFzXSAx2WWTvYBTci2Sxwk) I'm trying to run SDHD 2.20 and it won't run online because of this.

for game support ask on the discord not here
also not an issue
game will be online fine if matching server BAD
you are probably missing opts or forgot to set them in segatools.ini
