### ISSUE TITLE
您好，关于提供更多信息的请求

### ISSUE THREAD

**Issue by ShirleyQaQ23** [hykilpikonna/AquaDX#5]
你好，我来自中国大陆，我曾经发布过几乎所有的hdd转储，可是因为神必原因，它们被微软删除，请问您是否有关于maimaihdd 和alls system的备份，我也许需要它们来更好的重建maimai的历史。

**Comment by hykilpikonna** [comment]
如果是为了保存历史的话，https://bemaniso.ws 上面有比较完整的历代数据直到 Festival Plus，不过需要账号。我的数据源只下载了 130 和 135，可以加我的 discord `hykilp` 继续讨论

以及 [1cc discord](https://discord.gg/e7xffWFf9p) 上有一些被解包重新打包好的版本，如果不需要收藏原生 .app 的话可以考虑从这里下，但是需要注意查病毒
